version: '2.1'

services:

  users-db:
    container_name: users-db
    build: ./db
    ports:
        - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  users-service:
    container_name: users-service
    build: ./
    ports:
      - 5001:5000
    environment:
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - SECRET_KEY=my_precious
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - users-db

  web-service:
    container_name: web-service
    build:
      context: ./client-ts # Use TypeScript as default, change this ./client for plain Javascript
      args:
        - NODE_ENV=development
        - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    ports:
      - 9000:9000
    depends_on:
      users-service:
        condition: service_started
    links:
      - users-service

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    depends_on:
      users-service:
        condition: service_started
      web-service:
        condition: service_started
    links:
      - users-service
      - web-service

